<?php
$settings = $block->getDiscountSettings();
?>
<div data-bind="scope: 'Rahul-discountplugin'">
<div role="alert"  class="messages " id="success-message">
    <div  class="message-success success message" data-ui-id="message-success">
        <div>Settings saved Succesfully!!!</div>
    </div>
</div>

<div role="alert"  class="messages " id="failure-message">
    <div  class="message message-error error" data-ui-id="message-error">
        <div id="error-message"></div>
    </div>
</div>

<form id="vatdiscountform" method="post" class="form" action="<?php /* @noEscape */ echo $settings['url']; ?>">
    <input
            name="action_url" id="action_url"
            type="hidden"
            value="<?php /* @noEscape */ echo $block->formURL('/vatplugin/update'); ?>">
    <input name="form_key" type="hidden" value="<?php /* @noEscape */ echo $block->getFormKey()?>" />
    <input name="id" type="hidden" value="<?php /* @noEscape */ echo $settings['vatpluginid'];?>" />
    <fieldset>
        <legend>DiscountPlugin Settings</legend>
        <table class="data-grid data-grid-draggable">
            <tr>
                <td>Api Key</td>
                <td>
                    <input class="admin__control-text"
                           type="text" name="apikey"
                           value="<?php /* @noEscape */ echo $settings['apikey'];?>"
                           required>
                </td>
            </tr>
            <tr>
                <td>End Point</td>
                <td>
                    <input class="admin__control-text"
                           type="text" name="endpoint"
                           value="https://vatapi.com/v1/vat-number-check?vatid="
                           readonly="readonly" required>
                </td>
            </tr>
            <tr>
                <td colspan="2" align="center">
                    <input type="button" id="savesettings" class="action primary" name="submit" value="Save Settings">
                </td>
            </tr>
        </table>
    </fieldset>
</form>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Rahul_VatPlugin/js/component": {
            }
        }
    }
 </script>
